### ISSUE TITLE
Is this thing alive? No gem found on rubygems

### ISSUE THREAD

**Issue by jhubert** [influitive/apartment-activejob#3]
I'm looking at using ActiveJob in my app. Is this gem the way to go or should I go with something like the `apartment-sidekiq` option instead?

**Comment by desheikh** [comment]
Hi @jhubert no, this isn't active yet. I havn't really had time to spend on this for a while, but hopefully will push a release out soon.
If your using sidekiq, apartment-sidekiq would be the better option since you'll still be able to use the full set of sidekiq features. This gem is really intended for anyone using alternative queuing systems.

**Comment by jhubert** [comment]
Thanks for the response @desheikh. One more question.. If I'm using Sidekiq via ActiveJob, is the apartment-sidekiq gem still the way to go or is it just for people using Sidekiq directly?

**Comment by jhubert** [comment]
Just tested it with ActiveJob -> Sidekiq and it seems to work, so my assumption is that the answer is yes.

**Comment by desheikh** [comment]
@jhubert that's unintentional behaviour though since apartment-sidekiq was written before activejob was introduced. 

Unless it's required for your usecase, I'd suggest against it anyways since activejob with sidekiq has certain limitations.
see: https://github.com/mperham/sidekiq/wiki/Active-Job
